version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sytdb
      PG_DATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: db.admin@spaceyatech.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
      - ./db-servers.json:/pgadmin4/servers.json
    ports:
      - 5005:80
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
    
