@BASE_URL = http://localhost:5000

###
GET {{BASE_URL}}

###
GET {{BASE_URL}}/users

###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "firstName": "Ernest",
    "lastName": "Wambua",
    "email": "ernestwambua4@gmail.com",
    "phone": "+254712286396",
    "password": "password123"
}

###
GET {{BASE_URL}}/users/b2994cb0-bcd3-47b2-967a-f7724acc2c0a

###
PATCH {{BASE_URL}}/users/b2994cb0-bcd3-47b2-967a-f7724acc2c0a
Content-Type: application/json

{
    "avatar": "https://bit.ly/3Wgeq06"
}

###
DELETE {{BASE_URL}}/users/a74d149a-a154-4765-8a93-3074bba776c4

###
GET {{BASE_URL}}/blogs

###
POST {{BASE_URL}}/blogs
Content-Type: application/json

{
    "title": "Lorem Ipsum",
    "description": "lorem ipsum",
    "content": "Lorem ipsum dolor",
    "user": "1fe8099c-719e-49c3-bacf-bf2783963b0b"
}

###
POST {{BASE_URL}}/auth/signup
Content-Type: application/json

{
    "firstName": "Ernest",
    "lastName": "Wambua",
    "email": "ernestwambua5@gmail.com",
    "phone": "+254715286396",
    "password": "password123"
}

###
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "ernestwambua5@gmail.com",
    "password": "password123"
}

###
GET {{BASE_URL}}/auth/profile

###
GET {{BASE_URL}}/auth/logout