@BASE_URL = http://localhost:5000

###
GET {{BASE_URL}}

###
GET {{BASE_URL}}/users

###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "firstName": "Ernest",
    "lastName": "Wambua",
    "email": "ernestwambua8@gmail.com",
    "phone": "+254718286396",
    "password": "password123"
}

###
GET {{BASE_URL}}/users/b2994cb0-bcd3-47b2-967a-f7724acc2c0a

###
PATCH {{BASE_URL}}/users/b2994cb0-bcd3-47b2-967a-f7724acc2c0a
Content-Type: application/json


{
    "avatar": "https://bit.ly/3Wgeq06"
}

###
DELETE {{BASE_URL}}/users/a74d149a-a154-4765-8a93-3074bba776c4




###
POST {{BASE_URL}}/auth/signup
Content-Type: application/json

{
    "firstName": "Ernest",
    "lastName": "Wambua",
    "email": "ernestwambua8@gmail.com",
    "phone": "+254718286396",
    "password": "password123"
}

###
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "ernestwambua8@gmail.com",
    "password": "password123"
}

###
GET {{BASE_URL}}/auth/profile

###
GET {{BASE_URL}}/auth/logout

###
GET {{BASE_URL}}/blogs

###
GET {{BASE_URL}}/blogs/9866ffea-385f-4bdf-b78b-5fc8ffbda883

###
POST {{BASE_URL}}/blogs
Content-Type: application/json

{
    "title": "Lorem Ipsum",
    "description": "lorem ipsum",
    "content": "Lorem ipsum dolor"
}

###
GET {{BASE_URL}}/reactions

###
GET {{BASE_URL}}/reactions/14b5f3b0-89b0-497a-a1ac-4b30f3d55a3b

###
GET {{BASE_URL}}/reactions/count?blogId=9866ffea-385f-4bdf-b78b-5fc8ffbda883

###
POST {{BASE_URL}}/reactions
Content-Type: application/json

{
    "type": "downvote",
    "blogId": "9866ffea-385f-4bdf-b78b-5fc8ffbda883"
}

###
DELETE {{BASE_URL}}/reactions/14b5f3b0-89b0-497a-a1ac-4b30f3d55a3b